
services:

  databases:
    build:  .
    container_name: databases
    ports:
      - "${PORT:-8000}:8000"
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


